# Generated by Django 5.1.15 on 2026-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equally'), ('EXACT', 'Exact Amounts'), ('PERCENTAGE', 'Percentages'), ('SHARES', 'Shares'), ('ADJUSTMENT', 'By Adjustment')], default='EQUAL', max_length=15),
        ),
    ]
