# Generated by Django 5.1.15 on 2026-02-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_currency',
        ),
    ]
