# Generated by Django 5.1.15 on 2026-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='accounts_em_token_5f2b37_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='accounts_em_expires_f36bd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverificationtoken',
            name='accounts_em_used_at_ed014f_idx',
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user', 'expires_at'], name='accounts_em_user_id_b5ffac_idx'),
        ),
    ]
