# Generated by Django 5.1.15 on 2026-02-27 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_remove_group_default_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('EXPENSE_ADDED', 'Expense Added'), ('EXPENSE_DELETED', 'Expense Deleted'), ('SETTLEMENT_ADDED', 'Payment Recorded'), ('SETTLEMENT_DELETED', 'Payment Deleted'), ('GROUP_CREATED', 'Group Created'), ('USER_JOINED', 'User Joined')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_initiated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
